# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    exclude:
      - helm

pr:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: External Apis/external-common-build-pipeline

extends:
  template: maven-docker.yml@templates
  parameters:
    sonarQubeProject: external-dcsa-events-processor
    blackduckScanTags: dcsaevents
    deployable: true
    dockerRepository: 'external-dcsa-events-processor'
