apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcsa-test
  name: dcsa-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dcsa-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dcsa-test
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 1000m
